// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonAiResultsMedium: typeof import('virtual:vite-icons/carbon/ai-results-medium')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MdiLightFactory: typeof import('virtual:vite-icons/mdi-light/factory')['default']
    README: typeof import('./src/components/README.md')['default']
    RiBilibiliFill: typeof import('virtual:vite-icons/ri/bilibili-fill')['default']
    RiBilibiliLine: typeof import('virtual:vite-icons/ri/bilibili-line')['default']
  }
}

export { }
